[package]
name = "na_nbt-honggfuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
honggfuzz = "0.5"
bytes = "1.11"

[dependencies.na_nbt]
path = ".."

[[bin]]
name = "read_write"
path = "fuzz_targets/read_write.rs"
test = false
doc = false
bench = false
